stages:
    - build
    - packages

variables:
    GIT_SUBMODULE_STRATEGY: recursive


# build

.template-debug-build-linux: &debug-build-linux
    stage: build
    variables:
        BUILD_TYPE: "debug"
    script:
        - assets/build/build.sh
    tags:
        - linux

~centos-7:
    <<: *debug-build-linux
    image: registry.gitlab.com/nany-lang/nanyc:centos-7

~debian-8:
    <<: *debug-build-linux
    image: registry.gitlab.com/nany-lang/nanyc:debian-8

~debian-9:
    <<: *debug-build-linux
    image: registry.gitlab.com/nany-lang/nanyc:debian-9

~ubuntu-16.04:
    <<: *debug-build-linux
    image: registry.gitlab.com/nany-lang/nanyc:ubuntu-16.04

~ubuntu-17.04:
    <<: *debug-build-linux
    image: registry.gitlab.com/nany-lang/nanyc:ubuntu-17.04


# packages

.template-pkg-linux: &package-linux
    stage: packages
    variables:
        BUILD_TYPE: "release"
    script:
        - assets/build/build.sh
    tags:
        - linux
    artifacts:
        paths:
            - distrib/*.deb
            - distrib/*.rpm
        expire_in: 2 weeks

centos-7:
    <<: *package-linux
    image: registry.gitlab.com/nany-lang/nanyc:centos-7

debian-8:
    <<: *package-linux
    image: registry.gitlab.com/nany-lang/nanyc:debian-8

debian-9:
    <<: *package-linux
    image: registry.gitlab.com/nany-lang/nanyc:debian-9

ubuntu-16.04:
    <<: *package-linux
    image: registry.gitlab.com/nany-lang/nanyc:ubuntu-16.04

ubuntu-17.04:
    <<: *package-linux
    image: registry.gitlab.com/nany-lang/nanyc:ubuntu-17.04
