stages:
    - build
    - packages

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    VERBOSE: '1'


# build

.template-debug-build-linux: &debug-build-linux
    stage: build
    script:
        - mkdir -p build/bootstrap
        - cd build/bootstrap
        - cmake ../../bootstrap -DCMAKE_BUILD_TYPE=debug
        - cmake --build . --config debug --target all -- -j $(nproc)
        - cmake --build . --config debug --target check
    tags:
        - linux

~centos-7:
    <<: *debug-build-linux
    image: registry.gitlab.com/nany-lang/nanyc:centos-7

~debian-8:
    <<: *debug-build-linux
    image: registry.gitlab.com/nany-lang/nanyc:debian-8

~debian-9:
    <<: *debug-build-linux
    image: registry.gitlab.com/nany-lang/nanyc:debian-9

~ubuntu-16.04:
    <<: *debug-build-linux
    image: registry.gitlab.com/nany-lang/nanyc:ubuntu-16.04

~ubuntu-17.04:
    <<: *debug-build-linux
    image: registry.gitlab.com/nany-lang/nanyc:ubuntu-17.04


# packages

.template-pkg-linux: &package-linux
    stage: packages
    script:
        - mkdir -p build/bootstrap
        - cd build/bootstrap
        - cmake ../../bootstrap -DCMAKE_BUILD_TYPE=release
        - cmake --build . --config release --target all -- -j $(nproc)
        - cmake --build . --config release --target check
        - ([ ! -e /etc/debian_version ] || make packages-deb)
    tags:
        - linux
    artifacts:
        paths:
            - distrib/*.deb
            - distrib/*.rpm
        expire_in: 2 weeks

centos-7:
    <<: *package-linux
    image: registry.gitlab.com/nany-lang/nanyc:centos-7

debian-8:
    <<: *package-linux
    image: registry.gitlab.com/nany-lang/nanyc:debian-8

debian-9:
    <<: *package-linux
    image: registry.gitlab.com/nany-lang/nanyc:debian-9

ubuntu-16.04:
    <<: *package-linux
    image: registry.gitlab.com/nany-lang/nanyc:ubuntu-16.04

ubuntu-17.04:
    <<: *package-linux
    image: registry.gitlab.com/nany-lang/nanyc:ubuntu-17.04
