sudo: required
dist: trusty
language: cpp
os:
    - linux
compiler:
    - gcc
env:
    - BUILD_TYPE=debug
    - BUILD_TYPE=release
before_install:
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq gcc-4.9 g++-4.9 cmake uuid-dev; fi
    - if [ $TRAVIS_OS_NAME == macos ]; then brew install ossp-uuid; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then export NPROC=$(nproc); fi
    - if [ $TRAVIS_OS_NAME == macos ]; then export NPROC=1; fi
install:
    - if [ $TRAVIS_OS_NAME == linux -a "$CXX" == "g++" ]; then export CC="gcc-4.9"; fi
    - if [ $TRAVIS_OS_NAME == linux -a "$CXX" == "g++" ]; then export CXX="g++-4.9"; fi
script:
    - env
    - cd src/bootstrap
    - cmake . -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
    - make -j ${NPROC}
notifications:
    slack:
        rooms:
            - nany-lang:NDhqNi6nrPziAo9ciYkQy3h3#nany-qa
