sudo: required
dist: trusty
language: cpp
osx_image: xcode8.2
os:
    - linux
    - osx
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5
            - g++-5
            - cmake
            - uuid-dev
compiler:
    - gcc
env:
    - BUILD_TYPE=debug
    - BUILD_TYPE=release
script:
    - assets/build/build.sh
notifications:
    slack:
        rooms:
            - nany-lang:NDhqNi6nrPziAo9ciYkQy3h3#nany-qa
