sudo: required
language: cpp
matrix:
  include:
    - os: linux
      env: BUILD=debug   IMAGE=debian-8
      services:
          - docker
    - os: linux
      env: BUILD=release IMAGE=debian-8
      services:
          - docker
    - os: linux
      env: BUILD=debug   IMAGE=debian-9
      services:
          - docker
    - os: linux
      env: BUILD=release IMAGE=debian-9
      services:
          - docker
    - os: linux
      env: BUILD=debug   IMAGE=ubuntu-16.04
      services:
          - docker
    - os: linux
      env: BUILD=release IMAGE=ubuntu-16.04
      services:
          - docker
    - os: linux
      env: BUILD=debug   IMAGE=ubuntu-17.04
      services:
          - docker
    - os: linux
      env: BUILD=release IMAGE=ubuntu-17.04
      services:
          - docker
    - os: linux
      env: BUILD=debug   IMAGE=centos-7
      services:
          - docker
    - os: linux
      env: BUILD=release IMAGE=centos-7
      services:
          - docker
    - os: osx
      osx_image: xcode8.2
      env: BUILD=debug
    - os: osx
      osx_image: xcode8.2
      env: BUILD=release
script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then assets/build/build.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo -E assets/build/build-via-docker.sh "${IMAGE}"; fi
notifications:
    slack:
        rooms:
            - nany-lang:NDhqNi6nrPziAo9ciYkQy3h3#nany-qa
