sudo: required
dist: trusty
language: cpp
osx_image: xcode8
os:
    - linux
    - osx
compiler:
    - gcc
env:
    - BUILD_TYPE=debug
    - BUILD_TYPE=release
before_install:
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq build-essential gcc-4.9 g++-4.9 cmake uuid-dev; fi
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq gcc make bsdtar rpm lintian python-setuptools; fi
script:
    - assets/build/build.sh
notifications:
    slack:
        rooms:
            - nany-lang:NDhqNi6nrPziAo9ciYkQy3h3#nany-qa
